# Generated by Django 2.2.6 on 2019-11-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='f_name',
            new_name='first_name',
        ),
    ]
