# Generated by Django 2.2.6 on 2019-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0007_auto_20191205_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='STEMLABS', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='Admin', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
