# Generated by Django 2.2.5 on 2019-12-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0008_auto_20191205_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('physician', 'physician')], max_length=10),
        ),
    ]
