# Generated by Django 2.2.5 on 2019-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0010_auto_20191214_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
