# Generated by Django 2.2.5 on 2019-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0012_auto_20191215_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='images/profile/default_profile_kylie.jpg', upload_to='media/images/profile'),
        ),
    ]
