# Generated by Django 2.2.5 on 2019-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0014_auto_20191218_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='images/profile/default_profile_image.jpg', upload_to='images/profile'),
        ),
    ]
