# Generated by Django 2.2.6 on 2019-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('last_stocked', models.DateField(auto_now=True)),
            ],
        ),
    ]
