# Generated by Django 2.2.5 on 2019-12-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMPLAIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name_plural': 'Complaints'},
        ),
    ]
