# Generated by Django 2.2.5 on 2019-12-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0013_auto_20191215_1701'),
        ('COMPLAIN', '0002_auto_20191215_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='physicianComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('physician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.Physician')),
            ],
            options={
                'verbose_name_plural': 'Physician Complaints',
            },
        ),
    ]
