# Generated by Django 2.2.6 on 2019-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='average_value',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
