# Generated by Django 2.2.5 on 2019-12-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAB', '0002_auto_20191207_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='delivery_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='progress',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Waiting for receiver', 'Waiting for receiver'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
